SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_V_RANGE = (30.0, 60.0)
ASTEROID_SPLIT_A_VARIANCE = 10
ASTEROID_COLLISION_V_LOSS_RANGE = (0.85, 0.99)
ASTEROID_MASS_VARIANCE = (0.8, 1.1)
ASTEROID_SHOW_HITBOX = False

ASTEROID_STARTING_WAVE_MASS = ASTEROID_MAX_RADIUS * 6
ASTEROID_WAVE_MASS_INCREASE = ASTEROID_MAX_RADIUS * 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_COOLDOWN = 0.3 # seconds
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5